# Generated by Django 5.2.17 on 2026-09-25 03:07

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_google_and_two_factor'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEmailChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityEmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(db_index=True, max_length=64)),
                ('sent_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation_source',
            field=models.CharField(blank=True, choices=[('EMAIL', 'University email code'), ('GOOGLE_WORKSPACE', 'Google Workspace')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_affiliation',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('university_email'), name='accounts_user_university_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('affiliation_source__isnull', True), ('affiliation_verified_at__isnull', True), ('university_email__isnull', True), ('verified_affiliation__isnull', True)), models.Q(('affiliation_source__in', ['EMAIL', 'GOOGLE_WORKSPACE']), ('affiliation_verified_at__isnull', False), ('university_email__isnull', False), ('verified_affiliation__in', ['STUDENT', 'STAFF'])), _connector='OR'), name='accounts_user_verified_affiliation_consistent'),
        ),
        migrations.AddField(
            model_name='universityemailchallenge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_email_challenge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universityemailsend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
