# Generated by Django 5.2.17 on 2026-09-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_requires_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpdevice',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='totpdevice',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='user',
            name='email_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
