# Generated by Django 5.2.17 on 2026-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='block',
            name='faculty_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
