# Generated by Django 5.2.17 on 2026-10-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_block_faculty_name_block_faculty_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier; keep unchanged after publication.', max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('LIBRARY', 'Library'), ('OFFICE', 'Office'), ('HALL', 'Hall'), ('FOOD', 'Food'), ('OTHER', 'Other')], max_length=16)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, help_text='English description')),
                ('floor', models.PositiveSmallIntegerField(blank=True, help_text='0 = basement; leave blank if unknown', null=True)),
                ('map_element', models.CharField(blank=True, help_text='Existing SVG element only: block:A–I, barrel:A–D, entrance:MAIN/G/I, canteen', max_length=24)),
                ('opening_hours', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=16)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campus.block')),
                ('recommended_entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campus.entrance')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campus.room')),
            ],
            options={
                'ordering': ['slug'],
                'constraints': [models.CheckConstraint(condition=models.Q(('floor__isnull', True), models.Q(('floor__gte', 0), ('floor__lte', 4)), _connector='OR'), name='campus_place_valid_floor')],
            },
        ),
    ]
