# Generated by Django 5.2.17 on 2026-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_campusplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusplace',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campusplace',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='campusplace',
            name='map_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='campusplace',
            name='photo',
            field=models.CharField(blank=True, help_text='Project asset path under /campus/places/', max_length=200),
        ),
        migrations.AddField(
            model_name='campusplace',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campusplace',
            name='category',
            field=models.CharField(choices=[('LIBRARY', 'Library'), ('OFFICE', 'Office'), ('HALL', 'Hall'), ('AUDITORIUM', 'Auditorium'), ('FOOD', 'Food'), ('OTHER', 'Other')], max_length=16),
        ),
    ]
